---

name: "Github actions demo"
on:
  push:
    branches:
      - master
      - testing
	  
jobs:
  build:
    runs-on: ubuntu-20.04
	
    steps:
      - name: "current date and time"
        run: date
	shell: bash
		
      - name: "os release"
	run: cat /etc/os-release
	shell: bash
		
      - name: "current user"
	run: whoami
	shell: bash
		
      - name: "present working directory details before checkout"
	run: |
	  pwd
	  ls -al

      - name: "checkout repository"
	uses: actions/checkout@v3
		
      - name: "present working directory details before checkout"
	run: |
	  pwd
	  ls -al

      - name: "installing terraform"
	run: |
	  wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
	  unzip terraform_1.6.6_linux_amd64.zip
	  ./terraform version
	  
      - name: "executing script.sh"
	run: |
          chmod +x script.sh
          ./script.sh
